GET  http://127.0.0.1:8000/api/products HTTP/1.1
Authorization: Bearer 1|c1etEl9Nar8Tdup9Z6JzbN6U3dgJwAaWHleCmSH24864254a
Accept: application/json

###
POST http://127.0.0.1:8000/api/products
Content-Type: application/json
Accept: application/json

{
    "nombre":"berenjenas ",
    "descripcion":"berenjenas y mas cosas",
    "precio":10.99
}

###
POST http://127.0.0.1:8000/api/login
Content-Type: application/json
Accept: application/json
Authorization: Bearer 5|MNKO8ZsLhOX1JIOx2fcgU7mlAuoMIB6fzUPUBcUscb62b70f

{
    "email":"carmen2@gmail.com",
    "password":"password"
}

###

POST http://127.0.0.1:8000/api/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer 5|MNKO8ZsLhOX1JIOx2fcgU7mlAuoMIB6fzUPUBcUscb62b70f

###
POST http://127.0.0.1:8000/api/register
Content-Type: application/json
Accept: application/json

{
    "name":"carmen",
    "email":"carmen2@gmail.com",
    "password":"password"
}


###
PUT  http://127.0.0.1:8000/api/products/2
Content-Type: application/json
Accept: application/json


{
    "nombre":"berenjenasDFSD",
    "descripcion":"berenjenas y mas cosasHFJSDJHFJDSJ",
    "precio":10.99
}

###

DELETE http://127.0.0.1:8000/api/products/2
Accept: application/json

###
