GET  http://127.0.0.1:8000/api/products HTTP/1.1
Authorization: Bearer 3|QFLFQDi1oHIKWqTH1Ub1xzKoODM33cHJZnwKyZ59842dda7c
Accept: application/json

###

POST http://127.0.0.1:8000/api/products
Content-Type: application/json
Accept: application/json

{
    "nombre":"berenjenas ",
    "descripcion":"berenjenas y mas cosas",
    "precio":10.99
}

###

POST http://127.0.0.1:8000/api/login
Content-Type: application/json
Accept: application/json

{
    "email":"carmen@gmail.com",
    "password":"password"
}

###
PUT  http://127.0.0.1:8000/api/products/2
Content-Type: application/json
Accept: application/json

{
    "nombre":"berenjenasDFSD",
    "descripcion":"berenjenas y mas cosasHFJSDJHFJDSJ",
    "precio":10.99
}

###

DELETE http://127.0.0.1:8000/api/products/2
Accept: application/json

###
