GET http://localhost:8000/api/depart

###
GET http://localhost:8000/api/depart/40

###
POST http://localhost:8000/api/depart/create
Content-Type: application/json
{
    "depart_no":80,
    "dnombre":"Departamento de Pruebas",
    "loc":"Madrid"
}

###
PUT http://localhost:8000/api/depart/create
Content-Type: application/json
{
    "depart_no":80,
    "dnombre":"Departamento de Pruebas",
    "loc":"Barcelona"
}
###

DELETE http://localhost:8000/api/depart/40